openapi: 3.0.0
info:
  version: V1
  title: Malware/AV Attachment scanning APIs
  contact:
    email: vishnu.narayana@symphony.com
  license:
    name: Symphony
  description: >
    #### Description:
    This document outlines the API for the Malware Attachment scanning provided by Symphony.
paths:
  "/api/v1/attachments/malware-scan/state/{fileId}":
    parameters:
      - in: path
        name: fileId
        schema:
          type: string
        required: true
        description: File ID of the scanned attachment.
      - in: header
        name: sessionToken
        description: Session token obtained from Session Authenticate endpoint.
        required: true
        schema:
          type: string
    get:
      summary: Gets the scanning state of the attachment for the given fileId.
      description: >
        #### Description:
        "Gets the scanning state of the attachment, possible values: Pending, Ok, Bad, Unscannable, Expired etc."
      tags:
        - Malware-scanning
      responses:
        "200":
          description: OK response with the current state of attachment scanning.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MalwareScanningState"
        "400":
          description: The file Id does not exist.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: User not allowed to perform the action
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      summary: Updates the scanning state of the attachment after scanning process is
        complete for the given fileId.
      description: >
        #### Description:
        "Updates the scanning state of the attachment, allowed values: Ok, Bad, Unscannable, Expired."
      tags:
        - Malware-scanning
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MalwareScanningState"
      responses:
        "204":
          description: Updated successfully.
        "400":
          description: The file Id does not exist or invalid value for the scanning state.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: User not allowed to perform the action
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
servers:
  - url: https:///attachment/v4/
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message.
          example: Error message
    Link:
      type: object
      description: Link to the scanning details.
      properties:
        text:
          type: string
          description: Text of the link in details message.
        url:
          type: string
          description: URL of the scanning details.
    MalwareScanningStateDetails:
      type: object
      description: Contains the details of the scanning in case of BAD state.
      properties:
        message:
          type: string
          description: Details of scanning.
        link:
          $ref: "#/components/schemas/Link"
    MalwareScanningState:
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
            - BAD
            - UNSCANNABLE
            - EXPIRED
          description: Contains the result of scanning and some additional information.
        ttl:
          type: integer
          description: TTL timestamp in epoch seconds. After that point in time file shall be rescanned in case of download attempt.
        details:
          $ref: "#/components/schemas/MalwareScanningStateDetails"
