openapi: 3.0.0
info:
  version: V1
  title: Malware/AV Attachment scanning APIs
  contact:
    email: vishnu.narayana@symphony.com
  license:
    name: Symphony
  description: >
    #### Description:
    This document outlines the API for the Malware Attachment scanning provided by Symphony.
paths:
  "/scan/status/{fileId}":
    parameters:
      - in: path
        name: fileId
        schema:
          type: string
        required: true
        description: File ID of the scanned attachment.
      - in: header
        name: sessionToken
        description: Session token obtained from Session Authenticate endpoint.
        required: true
        schema:
          type: string
    get:
      summary: Gets the scanning status of the attachment for the given fileId and messageId.
      description: >
        #### Description:
        "Gets the scanning status of the attachment, possible values: Pending, Ok, Bad, Unscannable, Failed (TBD)."
      tags:
        - Malware-scanning
      responses:
        "200":
          description: OK response with the current state of attachment scanning.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScanningState"
        "400":
          description: The file Id does not exist.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: User not allowed to perform the action
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      summary: Updates the scanning status of the attachment after scanning process is
        complete for the given fileId (and messageId(s)).
      description: >
        #### Description:
        "Updates the scanning status of the attachment, allowed values: Ok, Bad, Unscannable, Failed, Expired."
      tags:
        - Malware-scanning
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                status:
                  description: "Scanning result state associated with FileID, allowed
                    values: Ok, Bad, Unscannable, Failed (TBD)."
                  type: string
              required:
                - status
      responses:
        "201":
          description: Updated successfully.
        "400":
          description: The file Id does not exist or invalid value for the scanning status.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: User not allowed to perform the action
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
servers:
  - url: https:///attachment/v4/
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message.
          example: Error message
    ScanningState:
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
            - BAD
            - UNSCANNABLE
            - FAILED
            - EXPIRED
          description: Scanning State.